// <auto-generated />
using System;
using DoacoesICCPVU.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DoacoesICCPVU.Migrations
{
    [DbContext(typeof(DoacaoContext))]
    partial class DoacaoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("DoacoesICCPVU.Models.Doacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Doador")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Donatario")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("EmitidoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Itens")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroOficio")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Doacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
